// The `find_usages` per-op notes — the op's user-facing documentation (§11: the schema + notes ARE
// the docs an agent reads through `status`). Split out of the op module purely to keep it under the
// line cap; the array stays the op definition's `notes` field, so a note still appears and vanishes
// with the op itself.

export const FIND_USAGES_NOTES: readonly string[] = [
  'on an oversized IN-PROCESS repo (> `ts.searchWarmMaxFiles`, default 4000 source files) this op REFUSES to warm the type-checker (a repo-wide reference fan-out would OOM and can kill the daemon) and says WHY the repo was not auto-escalated into a killable child (t-754922) plus the one remedy for that cause. `force:true` does NOT override it (forcing killed the daemon in production). No refusal in an escalated / configured process-mode child.',
  'role = what a ref syntactically IS: jsx (<X/> tags, closing deduped) · call · type · import · reexport (barrel `export {X} from` — never collapsed) · read · write · decl.',
  'role:read/write is SYNTACTIC (is the identifier read vs assigned) — it does NOT resolve store-field access: a zustand `useStore(s => s.count)` or a `set(...)` call reads as a `call`, not a read/write of `count`. Use it for variable/binding reads-vs-writes, not store-field tracing.',
  'collapseImports (default true): an import is hidden once its file also has a real usage (count returns as importsCollapsed); import-only files & re-exports always stay. collapseImports:false or role:import to list all. sql-mode keeps every import row.',
  "groupBy:'enclosing' rolls refs up to the nearest enclosing declaration ('which components render <X>'), sorted by count; encloser ids chain into other ops.",
  'filter {pathExclude/pathInclude globs, kind, exportedOnly}: dropped refs are reported as excludedByFilter — a filter never reads as completeness.',
  'symbols:[…] answers several targets in one sectioned call (unresolvable names → unresolved). A role filter matching 0 still prints the full role distribution + the dominant role to try.',
  "deleting a symbol? text:true adds comment/string/doc occurrences of the name, deduped against semantic refs and flagged 'text-only (identity NOT proven)' — role/path filters don't touch the text side.",
  'multi-program (see concepts: cross-program-read): each usage carries the `program` that surfaced it (sql column `program`). HONEST ASYMMETRY — a sibling label (tsconfig.test.json) means present ONLY there; the primary label means present in primary, POSSIBLY elsewhere too. Emitted only when >1 program is loaded.',
  'density (text/json, NOT sql): a column CONSTANT across the listed rows is hoisted to a header and dropped per-row — a single `role` filter → `role=<r>` (read effective role as `row.role ?? role`); the dominant program → `allProgram=<p>` (read `row.program ?? allProgram`). `listable` (collapsed-import count tie) appears ONLY when the rows are truncated. sql-mode keeps every value per row.',
  "mergeDeclarations:true — for an AMBIGUOUS name (the interface-decl + host-decl + impl triplet), union the usages of ALL same-named declarations instead of failing. The merged decls are listed in `mergedDeclarations`; each usage's `decls` indexes into it (per-site provenance — unrelated same-named symbols are never silently conflated). The ambiguous hard-FAIL surfaces this flag.",
  '{name, file} member fallback: when no TOP-LEVEL declaration of `name` lives in `file`, a class/type MEMBER, enum member, or re-exported binding of that name is resolved instead (the resolution is disclosed as a leading note); several such bindings → a pick-list + a member_usages redirect. So a method / type-member / re-export is not a dead-end.',
  'conditions:true (flat mode only) — annotate each site with the enclosing conditional-BRANCH chain it sits under, outermost→innermost with polarity applied: rendered `⟨a && !(b)⟩`, `⟨no branch⟩` for a MEASURED empty chain, and NOTHING when not annotated. sql column `condition`: the rendered chain · `\'\'` = measured "no enclosing branch" · NULL = not annotated (flag off, or a grouped/text row) — so filter conditional sites with `condition <> \'\'`, NEVER `IS NOT NULL` (that keeps every annotated row). Answers "where is X used AND WHEN" in ONE call instead of opening every site to recover the surrounding `if`.',
  'conditions:true SCOPE — syntactic branches inside the site\'s OWN function: if/else · ternary · &&/||-RHS (`??`-RHS as `lhs == null`) · logical-assignment RHS (`||=`/`&&=`/`??=`) · optional-chain arguments (`a?.b(F(x))` → `a != null`; a multi-link chain reports the NEAREST link, whose text carries the earlier `?.`s) · switch-case (fallthrough disjoined) · while/for test. A negated predicate is simplified, so the else of `if (!x)` reads `x` (not `!(!x)`) — don\'t filter negated branches by a `!(` prefix. A long predicate is itself cut with a TRAILING `…`. The chain is SOURCE text to READ, not an expression to evaluate: it can contain a call (`a?.b().c != null` — re-evaluating it would re-run side effects) or TS-only syntax (`o.m!.g != null`, which is not valid JS). An EMPTY chain means "no enclosing branch", NEVER "always runs": an early `return`/`throw` above the site, a conditionally-invoked caller, conditions outside a nested closure, iteration constructs (`for..of`, a `do..while` body), and DEFAULT values (a destructuring default `const {a = F()} = o` or a parameter default, which evaluate only when the value is `undefined`) are outside this claim — and that list is not exhaustive. A leading `<unstated>` means the chain is a SUBSET: a branch whose condition is not stated (a `default:`/`catch`, an unproven case-fallthrough, a chain over the 4-condition cap) or an annotation that could not be completed for that site. Ignored under groupBy (disclosed).',
  'auditing an ABSENCE — "which of these does NOT call F" (which ops lack a guard) — is a two-producer sql anti-join over THIS op, not a manual sweep: `concepts: absence-audit` in status carries the pasteable shape. ITS LIMITS: (1) the join key is `file`, sound only while each family member owns one file — run `SELECT file,COUNT(*) c FROM fam GROUP BY file HAVING c>1` first, since two members in one file HIDE the unguarded one; (2) a member whose F-call sits in a HELPER file reads as a hole, so with both producers COMPLETE the answer is an UPPER bound (a false alarm costs one read; a missed hole is the bug you were auditing for); (3) completeness is not free — an undiscovered-program floor makes a producer a LOWER bound (it surfaces as a `!! LOWER BOUND` note on the sql result) and a family member the factory-call producer misses drops an audit target, both of which HIDE a hole; (4) keep `role:\'call\'` on the F producer — sql-mode never collapses imports, so without it every importing file lands in the table with `condition = \'\'` and reads as an unconditional caller. Add conditions:true to the F producer to split "calls F" from "calls F only under a branch".',
  'props:{prop: true|value|values[]} — "which <X/> sites pass THIS prop (with THIS value)": the audit query for an escape-hatch prop (`props:{dirtyGuard:false}`) or a design-system variant (`props:{variant:["contained","low-contrast"]}`). `true` = passed with ANY value (so the LITERAL `true` — a bare `<X disabled/>` — is asked as `[\'true\']`); a string / number / `false` / an array of them = one of these LITERAL values; several entries are AND-ed. Implies role:\'jsx\' (an explicit other role is a bad_args, never a silent rewrite). Value spellings are NORMALIZED, so `x="a"`, `x={\'a\'}` compare equal, a bare `x` is `true`, and `{false}`/`{0}` are literals. Beats grep on BOTH sides: the component is resolved through the LS (an aliased `import {Button as B}` … `<B variant="contained"/>` counts), and a non-literal value (`{!isView}`) is a value grep cannot even see.',
  "props HONESTY (§3.3) — a site whose answer is not statically knowable is KEPT at confidence=dynamic, never dropped: (a) the prop is passed with a NON-LITERAL value (the expression source is in the row / `props` column as `name={expr}`), (b) the site carries a `{...spread}` that may CARRY the prop (attribute absent) or OVERRIDE it (a literal outside your value set). The two counts stay APART in `propsUncertain {dynamicValue, spreadMaybe}` + one `!!` note each, because the remedies differ — read the expression vs read what the spread holds. Non-matching jsx sites go to excludedByFilter (a filter never reads as completeness), and roleBreakdown.jsx is the denominator a `0` must be read against. Under groupBy the filter STILL applies (it runs before the rollup) and the group takes the WORST-of its sites' confidence; only the per-site value annotation is dropped (disclosed).",
  'destructures:true (flat mode only) — annotate each call site with the return-shape it consumes: `⇒{a,b}` destructured props (`const {a,b}=fn()`) or member-accessed (`fn().x`), a trailing `…` for a `...rest`/computed key (unknown extra props), `⇒whole` for a value bound/passed whole (may use ANY prop — conservative), `⇒{}` for a discarded result. Triages return-shape blast radius (which sites break if a return field changes) in ONE call; sql column `destructures`. Ignored under groupBy (disclosed).',
];
