// The `find_usages` per-op notes — the op's user-facing documentation (§11: the schema + notes ARE
// the docs an agent reads through `status`). Split out of the op module purely to keep it under the
// line cap; the array stays the op definition's `notes` field, so a note still appears and vanishes
// with the op itself.

export const FIND_USAGES_NOTES: readonly string[] = [
  'on an oversized IN-PROCESS repo (> `ts.searchWarmMaxFiles`, default 4000 source files) this op REFUSES to warm the type-checker (a repo-wide reference fan-out would OOM and can kill the daemon) and says WHY the repo was not auto-escalated into a killable child (t-754922) plus the one remedy for that cause. `force:true` does NOT override it (forcing killed the daemon in production). No refusal in an escalated / configured process-mode child.',
  'role = what a ref syntactically IS: jsx (<X/> tags, closing deduped) · call · type · import · reexport (barrel `export {X} from` — never collapsed) · read · write · decl.',
  'role:read/write is SYNTACTIC (is the identifier read vs assigned) — it does NOT resolve store-field access: a zustand `useStore(s => s.count)` or a `set(...)` call reads as a `call`, not a read/write of `count`. Use it for variable/binding reads-vs-writes, not store-field tracing.',
  'collapseImports (default true): an import is hidden once its file also has a real usage (count returns as importsCollapsed); import-only files & re-exports always stay. collapseImports:false or role:import to list all. sql-mode keeps every import row.',
  "groupBy:'enclosing' rolls refs up to the nearest enclosing declaration ('which components render <X>'), sorted by count; encloser ids chain into other ops.",
  'filter {pathExclude/pathInclude globs, kind, exportedOnly}: dropped refs are reported as excludedByFilter — a filter never reads as completeness.',
  'symbols:[…] answers several targets in one sectioned call (unresolvable names → unresolved). A role filter matching 0 still prints the full role distribution + the dominant role to try.',
  "deleting a symbol? text:true adds comment/string/doc occurrences of the name, deduped against semantic refs and flagged 'text-only (identity NOT proven)' — role/path filters don't touch the text side.",
  'multi-program (see concepts: cross-program-read): each usage carries the `program` that surfaced it (sql column `program`). HONEST ASYMMETRY — a sibling label (tsconfig.test.json) means present ONLY there; the primary label means present in primary, POSSIBLY elsewhere too. Emitted only when >1 program is loaded.',
  'density (text/json, NOT sql): a column CONSTANT across the listed rows is hoisted to a header and dropped per-row — a single `role` filter → `role=<r>` (read effective role as `row.role ?? role`); the dominant program → `allProgram=<p>` (read `row.program ?? allProgram`). `listable` (collapsed-import count tie) appears ONLY when the rows are truncated. sql-mode keeps every value per row.',
  "mergeDeclarations:true — for an AMBIGUOUS name (the interface-decl + host-decl + impl triplet), union the usages of ALL same-named declarations instead of failing. The merged decls are listed in `mergedDeclarations`; each usage's `decls` indexes into it (per-site provenance — unrelated same-named symbols are never silently conflated). The ambiguous hard-FAIL surfaces this flag.",
  '{name, file} member fallback: when no TOP-LEVEL declaration of `name` lives in `file`, a class/type MEMBER, enum member, or re-exported binding of that name is resolved instead (the resolution is disclosed as a leading note); several such bindings → a pick-list + a member_usages redirect. So a method / type-member / re-export is not a dead-end.',
  'conditions:true (flat mode only) — annotate each site with the enclosing conditional-BRANCH chain it sits under, rendered `⟨a && !(b)⟩` outermost→innermost with polarity applied (an `else` / `whenFalse` / `||`-RHS branch reads `!(cond)`); sql column `condition`. Answers "where is X used AND WHEN" in ONE call instead of opening every site to recover the surrounding `if`. SCOPE: syntactic branches inside the site\'s OWN function — if/else · ternary · &&/||-RHS (`??`-RHS as `lhs == null`) · switch-case (fallthrough disjoined) · while/for test. An EMPTY chain means "no enclosing branch", NEVER "always runs": an early `return`/`throw` above the site, a conditionally-invoked caller, and conditions outside a nested closure are OUT of scope. A leading `…` marks a real branch whose condition is not stated (a `default:`/`catch` branch, an unproven case-fallthrough, or a chain over the 4-condition cap) — the chain is then a subset, never presented as whole. Ignored under groupBy (disclosed).',
  'auditing an ABSENCE — "which of these does NOT call F" (which ops lack a guard) — is a two-producer sql anti-join over THIS op, not a manual sweep: see `concepts: absence-audit` in status for the shape and its two limits. Add conditions:true to the F producer to separate "calls F" from "calls F only under a condition".',
  'destructures:true (flat mode only) — annotate each call site with the return-shape it consumes: `⇒{a,b}` destructured props (`const {a,b}=fn()`) or member-accessed (`fn().x`), a trailing `…` for a `...rest`/computed key (unknown extra props), `⇒whole` for a value bound/passed whole (may use ANY prop — conservative), `⇒{}` for a discarded result. Triages return-shape blast radius (which sites break if a return field changes) in ONE call; sql column `destructures`. Ignored under groupBy (disclosed).',
];
